/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movie.seat.booking.system;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.*;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import static movie.seat.booking.system.Login.UnameField;

/**
 *
 * @author Me
 */
public class StaffDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MovieList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MovieType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        MovieName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Designation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NumberSeat = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        Price = new javax.swing.JFormattedTextField();
        Add = new javax.swing.JButton();
        DateTime = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        MovieList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Type", "Movie Name", "Date and Time", "Designation", "# Seat", "Taken Seat", "Price", "Total ", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MovieList.setCellSelectionEnabled(true);
        MovieList.setFillsViewportHeight(true);
        MovieList.setFocusCycleRoot(true);
        MovieList.setFocusable(false);
        MovieList.getTableHeader().setResizingAllowed(false);
        MovieList.getTableHeader().setReorderingAllowed(false);
        MovieList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MovieListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MovieList);
        if (MovieList.getColumnModel().getColumnCount() > 0) {
            MovieList.getColumnModel().getColumn(0).setResizable(false);
            MovieList.getColumnModel().getColumn(0).setPreferredWidth(150);
            MovieList.getColumnModel().getColumn(1).setResizable(false);
            MovieList.getColumnModel().getColumn(1).setPreferredWidth(250);
            MovieList.getColumnModel().getColumn(2).setResizable(false);
            MovieList.getColumnModel().getColumn(2).setPreferredWidth(100);
            MovieList.getColumnModel().getColumn(3).setResizable(false);
            MovieList.getColumnModel().getColumn(3).setPreferredWidth(75);
            MovieList.getColumnModel().getColumn(4).setResizable(false);
            MovieList.getColumnModel().getColumn(4).setPreferredWidth(50);
            MovieList.getColumnModel().getColumn(5).setResizable(false);
            MovieList.getColumnModel().getColumn(5).setPreferredWidth(50);
            MovieList.getColumnModel().getColumn(6).setResizable(false);
            MovieList.getColumnModel().getColumn(6).setPreferredWidth(50);
            MovieList.getColumnModel().getColumn(7).setResizable(false);
            MovieList.getColumnModel().getColumn(7).setPreferredWidth(50);
            MovieList.getColumnModel().getColumn(8).setResizable(false);
            MovieList.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1306, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movie List", jPanel2);

        jLabel1.setText("Movie Type:");

        MovieType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Action/Adventure", "Adventure", "Animation", "Biographical", "Comedy", "Crime", "Dark Comedy", "Drama", "Disaster", "Documentary", "Fantasy", "Film Noir", "Historical Fiction", "Historical Film", "Horror", "Musical", "Mystery", "Romance", "Romantic Comedy", "Science FIction", "Thriller", "War", "Western", " " }));

        jLabel2.setText("Movie Name:");

        jLabel3.setText("Date & Time:");

        jLabel5.setText("Designation:");

        Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesignationActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Number of Seats:");

        NumberSeat.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setText("Price:");

        Price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        DateTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MovieType, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MovieName)
                        .addComponent(Designation)
                        .addComponent(Add)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateTime, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                    .addComponent(NumberSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(818, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MovieType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Add)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Movie", jPanel3);

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesignationActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if(MovieName.getText().isBlank()){
            MovieName.setBackground(Color.red);
        }else if(Designation.getText().isBlank()){
            Designation.setBackground(Color.red);
        }else if(Price.getText().isBlank()){
            Price.setBackground(Color.red);
        }else{
             
             try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/movieseatbooking","root","root");
                Statement stmt = con.createStatement();
                DateTimeFormatter DTF = DateTimeFormatter.ofPattern("yyyyMMddHm");
                LocalDateTime now = LocalDateTime.now();
                String MovieID = MovieName.getText().substring(0,1) + DTF.format(now);
                String Moviename = MovieName.getText();
                String movietype = MovieType.getSelectedItem().toString();
                var datetime  = DateTime.getValue();

              String dateSet = new SimpleDateFormat("yyyy/MM/dd").format(datetime);
              String timeSet = new SimpleDateFormat("HH:mm").format(datetime);
              
                String designation = Designation.getText();
                String price = Price.getText();
          
                String numberseat = NumberSeat.getValue().toString();
                String sql = "Insert into movie Values ('" +MovieID + "','"+movietype+"','"+dateSet+"','"+timeSet+"','"+designation+"',"+numberseat+",'"+price+"',"+numberseat+",'"+Moviename+"')";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Movie Added", "Successful", 1);
                MovieType.setSelectedIndex(0);
                MovieName.setText("");
                Designation.setText("");
                Price.setText("");
                NumberSeat.setValue(0);
                RefreshTable();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         RefreshTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        RefreshTable();
    }//GEN-LAST:event_formWindowOpened

    private void MovieListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovieListMouseClicked
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/movieseatbooking","root","root");
            Statement stmt = con.createStatement();
            int selCell = MovieList.getSelectedColumn();
            var MovieType =  MovieList.getValueAt(MovieList.getSelectedRow(), 0);
            var MovieName = MovieList.getValueAt(MovieList.getSelectedRow(), 1);
            if(selCell == 8){
                int opt = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this movie: "+MovieName+"?","Confirm",1);
                if (opt == 0){
                    String sqlup = "delete from movie  where MovieType='"+MovieType+"' and MovieName='"+MovieName+"'";
                    stmt.executeUpdate(sqlup);
                    RefreshTable();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StaffDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StaffDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MovieListMouseClicked
    public static void RefreshTable(){
    try {
                
                DefaultTableModel tableModel = (DefaultTableModel) MovieList.getModel();
                tableModel.setRowCount(0);
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/movieseatbooking","root","root");
                Statement stmt = con.createStatement();
                ResultSet RS = stmt.executeQuery("Select * from movie");
                int ctr = 0;
               // String[] columnNames = {"Movie Type", "Movie Name", "Date and Time", "Designation", "# Seat", "Taken Seat", "Price", "Total ", "Action"};
              //  DefaultTableModel tableModel = new DefaultTableModel(columnNames,0);
                
                while(RS.next()){
                    String mtype = RS.getString("MovieType");
                    String mname = RS.getString("MovieName");
                    String date = RS.getString("Date");
                    String time = RS.getString("Time");
                    
                    String designation = RS.getString("Designation");
                    String nseat = RS.getString("NSeat");
                    String remaining = RS.getString("Remaining");
                    String price = RS.getString("Price");
                    int total = 0;
                    
                                   
                    tableModel.addRow(new Object[] {mtype,mname,date+" "+time,designation,nseat,remaining,price,String.valueOf(total),"Click to delete"});
                    ctr++;
                } 
                if(ctr==0){
                JOptionPane.showMessageDialog(null,"No result", "Successful", 1);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        RefreshTable();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDashboard().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JSpinner DateTime;
    private javax.swing.JTextField Designation;
    private static javax.swing.JTable MovieList;
    private javax.swing.JTextField MovieName;
    private javax.swing.JComboBox<String> MovieType;
    private javax.swing.JSpinner NumberSeat;
    private javax.swing.JFormattedTextField Price;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
